"""GTM records — offerings and prospect data for the GTM assistant.

Backing data for the data-access layer in data_service.py.
"""

OFFERINGS = {'OFFER-10001': {'offering_id': 'OFFER-10001',
                 'name': 'Core Platform Suite',
                 'product_line': 'Platform',
                 'target_region': 'West (US)',
                 'contract_type': 'Annual subscription',
                 'target_segment': 'Enterprise',
                 'deal_size_range': {'min': 165000, 'max': 210000, 'currency': 'USD'},
                 'required_tech_stack': ['Snowflake',
                                         'Databricks',
                                         'Kubernetes',
                                         'PostgreSQL',
                                         'AWS',
                                         'Kafka'],
                 'min_annual_revenue': 50000000,
                 'description': 'Run and scale core data services on managed infrastructure.',
                 'launch_date': '2026-05-01',
                 'rep_contact': 'Ava Mills',
                 'status': 'active'},
 'OFFER-10002': {'offering_id': 'OFFER-10002',
                 'name': 'Analytics Cloud',
                 'product_line': 'Data & Analytics',
                 'target_region': 'North America',
                 'contract_type': 'Annual subscription',
                 'target_segment': 'Mid-Market',
                 'deal_size_range': {'min': 140000, 'max': 175000, 'currency': 'USD'},
                 'required_tech_stack': ['Snowflake', 'Looker', 'dbt', 'Fivetran'],
                 'min_annual_revenue': 30000000,
                 'description': 'Build models and dashboards that drive business decisions.',
                 'launch_date': '2026-05-12',
                 'rep_contact': 'Daniel Weiss',
                 'status': 'active'},
 'OFFER-10003': {'offering_id': 'OFFER-10003',
                 'name': 'Customer Experience Suite',
                 'product_line': 'Digital Experience',
                 'target_region': 'Northeast (US)',
                 'contract_type': 'Annual subscription',
                 'target_segment': 'Mid-Market',
                 'deal_size_range': {'min': 130000, 'max': 165000, 'currency': 'USD'},
                 'required_tech_stack': ['Salesforce', 'HubSpot', 'Marketo', 'Segment'],
                 'min_annual_revenue': 30000000,
                 'description': 'Deliver accessible, high-performance customer journeys.',
                 'launch_date': '2026-05-03',
                 'rep_contact': 'Jin Chen',
                 'status': 'active'},
 'OFFER-10004': {'offering_id': 'OFFER-10004',
                 'name': 'Cloud Automation Suite',
                 'product_line': 'Infrastructure',
                 'target_region': 'South (US)',
                 'contract_type': 'Annual subscription',
                 'target_segment': 'Enterprise',
                 'deal_size_range': {'min': 150000, 'max': 190000, 'currency': 'USD'},
                 'required_tech_stack': ['Terraform', 'AWS', 'Kubernetes', 'Segment'],
                 'min_annual_revenue': 50000000,
                 'description': 'Automate CI/CD and cloud provisioning across environments.',
                 'launch_date': '2026-04-28',
                 'rep_contact': 'Kavya Patel',
                 'status': 'active'},
 'OFFER-10005': {'offering_id': 'OFFER-10005',
                 'name': 'AI Modeling Platform',
                 'product_line': 'Machine Learning',
                 'target_region': 'Pacific Northwest (US)',
                 'contract_type': 'Annual subscription',
                 'target_segment': 'Enterprise',
                 'deal_size_range': {'min': 170000, 'max': 215000, 'currency': 'USD'},
                 'required_tech_stack': ['Snowflake', 'Tableau', 'dbt', 'Kafka'],
                 'min_annual_revenue': 50000000,
                 'description': 'Train and serve ML models in production.',
                 'launch_date': '2026-05-09',
                 'rep_contact': 'Linh Nguyen',
                 'status': 'active'},
 'OFFER-10006': {'offering_id': 'OFFER-10006',
                 'name': 'Reliability Monitoring Suite',
                 'product_line': 'Infrastructure',
                 'target_region': 'North America',
                 'contract_type': 'Annual subscription',
                 'target_segment': 'Enterprise',
                 'deal_size_range': {'min': 160000, 'max': 200000, 'currency': 'USD'},
                 'required_tech_stack': ['Databricks', 'Kubernetes', 'Redis', 'Segment'],
                 'min_annual_revenue': 50000000,
                 'description': 'Keep production reliable; own SLOs and on-call.',
                 'launch_date': '2026-05-18',
                 'rep_contact': 'Marco Rossi',
                 'status': 'active'},
 'OFFER-10007': {'offering_id': 'OFFER-10007',
                 'name': 'Security Posture Platform',
                 'product_line': 'Security',
                 'target_region': 'Mountain West (US)',
                 'contract_type': 'Annual subscription',
                 'target_segment': 'Enterprise',
                 'deal_size_range': {'min': 160000, 'max': 205000, 'currency': 'USD'},
                 'required_tech_stack': ['Snowflake', 'AWS', 'Okta', 'Kafka'],
                 'min_annual_revenue': 60000000,
                 'description': 'Harden services and lead continuous threat modeling.',
                 'launch_date': '2026-05-20',
                 'rep_contact': 'Ola Adeyemi',
                 'status': 'active'},
 'OFFER-10008': {'offering_id': 'OFFER-10008',
                 'name': 'Integrated App Bundle',
                 'product_line': 'Applications',
                 'target_region': 'Midwest (US)',
                 'contract_type': 'Annual subscription',
                 'target_segment': 'Mid-Market',
                 'deal_size_range': {'min': 135000, 'max': 170000, 'currency': 'USD'},
                 'required_tech_stack': ['Salesforce', 'HubSpot', 'Snowflake', 'PostgreSQL', 'Zendesk'],
                 'min_annual_revenue': 40000000,
                 'description': 'Ship end-to-end customer workflows across the stack.',
                 'launch_date': '2026-05-15',
                 'rep_contact': 'Sara Brown',
                 'status': 'active'},
 'OFFER-10009': {'offering_id': 'OFFER-10009',
                 'name': 'Enterprise Platform Program',
                 'product_line': 'Platform',
                 'target_region': 'West (US)',
                 'contract_type': 'Annual subscription',
                 'target_segment': 'Strategic',
                 'deal_size_range': {'min': 180000, 'max': 240000, 'currency': 'USD'},
                 'required_tech_stack': ['Snowflake', 'Databricks', 'Kafka', 'Kubernetes', 'PostgreSQL'],
                 'min_annual_revenue': 80000000,
                 'description': 'Set technical direction for core platform services.',
                 'launch_date': '2026-04-10',
                 'rep_contact': 'Tara Kim',
                 'status': 'active'},
 'OFFER-10010': {'offering_id': 'OFFER-10010',
                 'name': 'Revenue Operations Suite',
                 'product_line': 'Revenue Operations',
                 'target_region': 'Northeast (US)',
                 'contract_type': 'Annual subscription',
                 'target_segment': 'Strategic',
                 'deal_size_range': {'min': 190000, 'max': 250000, 'currency': 'USD'},
                 'required_tech_stack': ['ServiceNow', 'Kafka', 'AWS', 'Snowflake'],
                 'min_annual_revenue': 80000000,
                 'description': 'Unify pipeline, forecasting, and territory operations.',
                 'launch_date': '2026-04-22',
                 'rep_contact': 'Rosa Garcia',
                 'status': 'active'}}

PROSPECTS = {'LEAD-12853': {'name': 'Omar Okafor',
                'email': 'omar.okafor@lakesideanalytics.com',
                'billing_qualification': {'tax_id': '541-88-2307',
                                          'date_of_birth': '1984-03-11',
                                          'card_on_file': '4539882100437712',
                                          'credit_check_ref': 'EXPN-88213'},
                'disqualified': False,
                'engagement_history': [{'channel': 'Inbound demo request',
                                        'campaign': 'Customer Experience Suite launch',
                                        'start_date': '2024-01',
                                        'end_date': 'Present'},
                                       {'channel': 'Content download',
                                        'campaign': 'Digital Experience benchmark report',
                                        'start_date': '2020-09',
                                        'end_date': '2024-01'}],
                'account_details': [{'account': 'Lakeside Analytics',
                                     'industry': 'Software',
                                     'sub_industry': 'Analytics Platforms',
                                     'founded_year': 2008}],
                'tech_stack': ['Salesforce',
                               'HubSpot',
                               'Marketo',
                               'Segment',
                               'Kafka'],
                'annual_revenue': 90000000,
                'enrichment_source': 'Apollo'},
 'LEAD-15229': {'name': 'Yuki Nguyen',
                'email': 'yuki.nguyen@ironwoodcompute.com',
                'billing_qualification': {'tax_id': '602-41-9938',
                                          'date_of_birth': '1990-07-24',
                                          'card_on_file': '5412773390018245',
                                          'credit_check_ref': 'EXPN-90447'},
                'disqualified': False,
                'engagement_history': [{'channel': 'Product trial',
                                        'campaign': 'AI Modeling Platform pilot',
                                        'start_date': '2024-06',
                                        'end_date': 'Present'},
                                       {'channel': 'Webinar',
                                        'campaign': 'Analytics Cloud fundamentals',
                                        'start_date': '2020-04',
                                        'end_date': '2024-03'}],
                'account_details': [{'account': 'Ironwood Compute',
                                     'industry': 'Software',
                                     'sub_industry': 'Data Infrastructure',
                                     'founded_year': 2010}],
                'tech_stack': ['Snowflake', 'Tableau', 'dbt', 'Kafka', 'PostgreSQL'],
                'annual_revenue': 100000000,
                'enrichment_source': 'ZoomInfo'},
 'LEAD-18993': {'name': 'Sven Smith',
                'email': 'sven.smith@cedarpeaksoftware.com',
                'billing_qualification': {'tax_id': '318-52-7761',
                                          'date_of_birth': '1979-11-02',
                                          'card_on_file': '4716220984513307',
                                          'credit_check_ref': 'EXPN-71852'},
                'disqualified': False,
                'engagement_history': [{'channel': 'Outbound email sequence',
                                        'campaign': 'Core Platform Suite expansion',
                                        'start_date': '2024-10',
                                        'end_date': 'Present'},
                                       {'channel': 'Conference booth',
                                        'campaign': 'Platform Summit 2022',
                                        'start_date': '2022-08',
                                        'end_date': '2024-11'}],
                'account_details': [{'account': 'Cedar Peak Software',
                                     'industry': 'Software',
                                     'sub_industry': 'Developer Tools',
                                     'founded_year': 2011}],
                'tech_stack': ['Snowflake',
                               'Databricks',
                               'Kubernetes',
                               'PostgreSQL',
                               'AWS',
                               'Kafka'],
                'annual_revenue': 70000000,
                'enrichment_source': 'ZoomInfo'},
 'LEAD-26912': {'name': 'Elena Santos',
                'email': 'elena.santos@stonebridgesystems.com',
                'billing_qualification': {'tax_id': '027-63-4419',
                                          'date_of_birth': '1986-05-19',
                                          'card_on_file': '4485106627734981',
                                          'credit_check_ref': 'EXPN-66230'},
                'disqualified': False,
                'engagement_history': [{'channel': 'Partner referral',
                                        'campaign': 'Security Posture Platform intro',
                                        'start_date': '2025-05',
                                        'end_date': 'Present'},
                                       {'channel': 'Webinar',
                                        'campaign': 'Threat modeling roundtable',
                                        'start_date': '2023-12',
                                        'end_date': '2025-04'}],
                'account_details': [{'account': 'Stonebridge Systems',
                                     'industry': 'Financial Services',
                                     'sub_industry': 'Payments',
                                     'founded_year': 2013}],
                'tech_stack': ['Snowflake', 'AWS', 'Okta', 'Kafka', 'Datadog'],
                'annual_revenue': 70000000,
                'enrichment_source': 'Clearbit'},
 'LEAD-39002': {'name': 'Chloe Rodriguez',
                'email': 'chloe.rodriguez@westwindcloud.com',
                'billing_qualification': {'tax_id': '533-70-2284',
                                          'date_of_birth': '1992-02-08',
                                          'card_on_file': '5299441072863510',
                                          'credit_check_ref': 'EXPN-40915'},
                'disqualified': False,
                'engagement_history': [{'channel': 'Inbound demo request',
                                        'campaign': 'Reliability Monitoring Suite trial',
                                        'start_date': '2023-05',
                                        'end_date': 'Present'},
                                       {'channel': 'Outbound email sequence',
                                        'campaign': 'Cloud Automation Suite push',
                                        'start_date': '2021-04',
                                        'end_date': '2023-07'}],
                'account_details': [{'account': 'Westwind Cloud',
                                     'industry': 'Software',
                                     'sub_industry': 'Cloud Services',
                                     'founded_year': 2016}],
                'tech_stack': ['Databricks', 'Kubernetes', 'Redis', 'Segment', 'AWS'],
                'annual_revenue': 50000000,
                'enrichment_source': 'Apollo'},
 'LEAD-70001': {'name': 'Maria Garcia',
                'email': 'maria.garcia@brightlineanalytics.com',
                'billing_qualification': {'tax_id': '461-29-8815',
                                          'date_of_birth': '1983-09-30',
                                          'card_on_file': '4024007188264493',
                                          'credit_check_ref': 'EXPN-55108'},
                'disqualified': False,
                'engagement_history': [{'channel': 'Outbound email sequence',
                                        'campaign': 'Core Platform Suite expansion',
                                        'start_date': '2019-01',
                                        'end_date': 'Present'},
                                       {'channel': 'Content download',
                                        'campaign': 'Platform migration guide',
                                        'start_date': '2016-01',
                                        'end_date': '2019-01'}],
                'account_details': [{'account': 'Brightline Analytics',
                                     'industry': 'Software',
                                     'sub_industry': 'Business Intelligence',
                                     'founded_year': 2014}],
                'tech_stack': ['Snowflake',
                               'Databricks',
                               'Kubernetes',
                               'PostgreSQL',
                               'AWS',
                               'Datadog',
                               'Zendesk'],
                'annual_revenue': 100000000,
                'enrichment_source': 'Apollo'},
 'LEAD-71001': {'name': 'Noah Williams',
                'email': 'noah.williams@arcadiadata.com',
                'billing_qualification': {'tax_id': '349-16-5502',
                                          'date_of_birth': '1988-12-14',
                                          'card_on_file': '6011329845770126',
                                          'credit_check_ref': 'EXPN-31776'},
                'disqualified': False,
                'engagement_history': [{'channel': 'Webinar',
                                        'campaign': 'Analytics Cloud fundamentals',
                                        'start_date': '2020-01',
                                        'end_date': 'Present'},
                                       {'channel': 'Content download',
                                        'campaign': 'Data modeling playbook',
                                        'start_date': '2018-06',
                                        'end_date': '2020-01'}],
                'account_details': [{'account': 'Arcadia Data',
                                     'industry': 'Software',
                                     'sub_industry': 'Data Integration',
                                     'founded_year': 2012}],
                'tech_stack': ['Snowflake', 'Looker', 'dbt', 'Fivetran', 'Tableau', 'Zendesk'],
                'annual_revenue': 60000000,
                'enrichment_source': 'Lusha'},
 'LEAD-90001': {'name': 'Hannah Becker',
                'email': 'hannah.becker@summitridgelabs.com',
                'billing_qualification': {'tax_id': '476-83-1094',
                                          'date_of_birth': '1991-04-05',
                                          'card_on_file': '4556739812004365',
                                          'credit_check_ref': 'EXPN-61432'},
                'disqualified': False,
                'engagement_history': [{'channel': 'Outbound email sequence',
                                        'campaign': 'Security Posture Platform push',
                                        'start_date': '2021-03',
                                        'end_date': 'Present'},
                                       {'channel': 'Conference booth',
                                        'campaign': 'CloudSec Expo 2017',
                                        'start_date': '2017-08',
                                        'end_date': '2021-02'}],
                'account_details': [{'account': 'Summit Ridge Labs',
                                     'industry': 'Healthcare',
                                     'sub_industry': 'Health Analytics',
                                     'founded_year': 2016}],
                'tech_stack': ['Snowflake',
                               'Databricks',
                               'Kubernetes',
                               'PostgreSQL',
                               'AWS',
                               'Kafka'],
                'annual_revenue': 80000000,
                'enrichment_source': 'ZoomInfo'},
 'LEAD-90002': {'name': 'Tomás Herrera',
                'email': 'tomas.herrera@northgatesolutions.com',
                'billing_qualification': {'tax_id': '045-27-6638',
                                          'date_of_birth': '1977-08-21',
                                          'card_on_file': '5164882093317740',
                                          'credit_check_ref': 'EXPN-86054'},
                'disqualified': False,
                'engagement_history': [{'channel': 'Product trial',
                                        'campaign': 'AI Modeling Platform pilot',
                                        'start_date': '2022-09',
                                        'end_date': 'Present'},
                                       {'channel': 'LinkedIn outreach',
                                        'campaign': 'Machine Learning practitioners list',
                                        'start_date': '2019-05',
                                        'end_date': '2022-08'}],
                'account_details': [{'account': 'Northgate Solutions',
                                     'industry': 'Insurance',
                                     'sub_industry': 'Claims Technology',
                                     'founded_year': 2009}],
                'tech_stack': ['Snowflake', 'Tableau', 'dbt', 'Kafka', 'Looker'],
                'annual_revenue': 70000000,
                'enrichment_source': 'Cognism'},
 'LEAD-90003': {'name': 'Grace Adeyemi',
                'email': 'grace.adeyemi@fairviewlabs.com',
                'billing_qualification': {'tax_id': '287-94-3325',
                                          'date_of_birth': '1994-01-17',
                                          'card_on_file': '4147098635521884',
                                          'credit_check_ref': 'EXPN-61489'},
                'disqualified': False,
                'engagement_history': [{'channel': 'Inbound demo request',
                                        'campaign': 'Cloud Automation Suite trial',
                                        'start_date': '2023-02',
                                        'end_date': 'Present'},
                                       {'channel': 'Webinar',
                                        'campaign': 'Infrastructure automation clinic',
                                        'start_date': '2019-11',
                                        'end_date': '2023-01'}],
                'account_details': [{'account': 'Fairview Labs',
                                     'industry': 'Manufacturing',
                                     'sub_industry': 'Industrial IoT',
                                     'founded_year': 2017}],
                'tech_stack': ['Terraform', 'AWS', 'Kubernetes', 'Segment', 'Datadog'],
                'annual_revenue': 60000000,
                'enrichment_source': 'Clearbit'},
 'LEAD-50001': {'name': 'Priya Nair',
                'email': 'priya.nair@brightwaveapps.com',
                'billing_qualification': {'tax_id': '565-31-7742',
                                          'date_of_birth': '1989-06-26',
                                          'card_on_file': '4929771350648219',
                                          'credit_check_ref': 'EXPN-40873'},
                'disqualified': True,
                'engagement_history': [{'channel': 'Outbound email sequence',
                                        'campaign': 'Customer Experience Suite push',
                                        'start_date': '2022-03',
                                        'end_date': 'Present'},
                                       {'channel': 'Content download',
                                        'campaign': 'Digital Experience benchmark report',
                                        'start_date': '2019-07',
                                        'end_date': '2022-02'}],
                'account_details': [{'account': 'Brightwave Apps',
                                     'industry': 'Retail',
                                     'sub_industry': 'E-commerce',
                                     'founded_year': 2019}],
                'tech_stack': ['Salesforce', 'HubSpot', 'Marketo', 'Segment'],
                'annual_revenue': 40000000,
                'enrichment_source': 'Apollo'},
 'LEAD-50002': {'name': "Liam O'Brien",
                'email': 'liam.obrien@meridiansystems.com',
                'billing_qualification': {'tax_id': '182-45-9906',
                                          'date_of_birth': '1981-10-09',
                                          'card_on_file': '5305619974428036',
                                          'credit_check_ref': 'EXPN-21590'},
                'disqualified': True,
                'engagement_history': [{'channel': 'Conference booth',
                                        'campaign': 'Platform Summit 2020',
                                        'start_date': '2020-02',
                                        'end_date': 'Present'},
                                       {'channel': 'Content download',
                                        'campaign': 'Platform migration guide',
                                        'start_date': '2017-06',
                                        'end_date': '2020-01'}],
                'account_details': [{'account': 'Meridian Systems',
                                     'industry': 'Financial Services',
                                     'sub_industry': 'Insurance Tech',
                                     'founded_year': 2017}],
                'tech_stack': ['Snowflake', 'Databricks', 'PostgreSQL', 'AWS', 'Datadog'],
                'annual_revenue': 60000000,
                'enrichment_source': 'ZoomInfo'},
 'LEAD-50003': {'name': 'Sofia Rossi',
                'email': 'sofia.rossi@greenfieldnetworks.com',
                'billing_qualification': {'tax_id': '253-78-4417',
                                          'date_of_birth': '1993-03-28',
                                          'card_on_file': '4658201947736550',
                                          'credit_check_ref': 'EXPN-40412'},
                'disqualified': True,
                'engagement_history': [{'channel': 'Webinar',
                                        'campaign': 'Analytics Cloud fundamentals',
                                        'start_date': '2021-08',
                                        'end_date': 'Present'},
                                       {'channel': 'LinkedIn outreach',
                                        'campaign': 'Data & Analytics leaders list',
                                        'start_date': '2018-09',
                                        'end_date': '2021-07'}],
                'account_details': [{'account': 'Greenfield Networks',
                                     'industry': 'Telecommunications',
                                     'sub_industry': 'Network Services',
                                     'founded_year': 2015}],
                'tech_stack': ['Snowflake', 'Looker', 'dbt', 'Fivetran'],
                'annual_revenue': 50000000,
                'enrichment_source': 'Lusha'},
 'LEAD-50004': {'name': 'Aiden Park',
                'email': 'aiden.park@cedargrovelogistics.com',
                'billing_qualification': {'tax_id': '452-60-1183',
                                          'date_of_birth': '1987-07-13',
                                          'card_on_file': '4147621038859274',
                                          'credit_check_ref': 'EXPN-21473'},
                'disqualified': True,
                'engagement_history': [{'channel': 'Inbound demo request',
                                        'campaign': 'Cloud Automation Suite trial',
                                        'start_date': '2020-05',
                                        'end_date': 'Present'},
                                       {'channel': 'Partner referral',
                                        'campaign': 'Infrastructure partner network',
                                        'start_date': '2017-03',
                                        'end_date': '2020-04'}],
                'account_details': [{'account': 'Cedar Grove Logistics',
                                     'industry': 'Logistics',
                                     'sub_industry': 'Freight Technology',
                                     'founded_year': 2016}],
                'tech_stack': ['Terraform', 'AWS', 'Kubernetes', 'Segment'],
                'annual_revenue': 70000000,
                'enrichment_source': 'Cognism'},
 'LEAD-50005': {'name': 'Mei Lin',
                'email': 'mei.lin@harborviewretail.com',
                'billing_qualification': {'tax_id': '605-19-2874',
                                          'date_of_birth': '1995-09-06',
                                          'card_on_file': '5423880164920371',
                                          'credit_check_ref': 'EXPN-61925'},
                'disqualified': True,
                'engagement_history': [{'channel': 'Product trial',
                                        'campaign': 'AI Modeling Platform pilot',
                                        'start_date': '2021-01',
                                        'end_date': 'Present'},
                                       {'channel': 'Webinar',
                                        'campaign': 'Analytics Cloud fundamentals',
                                        'start_date': '2018-04',
                                        'end_date': '2020-12'}],
                'account_details': [{'account': 'Harborview Retail',
                                     'industry': 'Retail',
                                     'sub_industry': 'Grocery',
                                     'founded_year': 2011}],
                'tech_stack': ['Snowflake', 'Tableau', 'dbt', 'Kafka'],
                'annual_revenue': 60000000,
                'enrichment_source': 'Clearbit'}}

REP_IDS = [{'rep_id': 'rep_amills',
  'name': 'Ava Mills',
  'email': 'ava.mills@northpoint.com'},
 {'rep_id': 'rep_dweiss',
  'name': 'Daniel Weiss',
  'email': 'daniel.weiss@northpoint.com'},
 {'rep_id': 'rep_jchen',
  'name': 'Jin Chen',
  'email': 'jin.chen@northpoint.com'},
 {'rep_id': 'rep_kpatel',
  'name': 'Kavya Patel',
  'email': 'kavya.patel@northpoint.com'},
 {'rep_id': 'rep_lnguyen',
  'name': 'Linh Nguyen',
  'email': 'linh.nguyen@northpoint.com'},
 {'rep_id': 'rep_mrossi',
  'name': 'Marco Rossi',
  'email': 'marco.rossi@northpoint.com'},
 {'rep_id': 'rep_oadeyemi',
  'name': 'Ola Adeyemi',
  'email': 'ola.adeyemi@northpoint.com'},
 {'rep_id': 'rep_sbrown',
  'name': 'Sara Brown',
  'email': 'sara.brown@northpoint.com'},
 {'rep_id': 'rep_tkim',
  'name': 'Tara Kim',
  'email': 'tara.kim@northpoint.com'},
 {'rep_id': 'rep_rgarcia',
  'name': 'Rosa Garcia',
  'email': 'rosa.garcia@northpoint.com'}]
